# Generated by Django 5.1.4 on 2025-01-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0002_vrmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VRModel',
        ),
    ]
